### ISSUE TITLE
Check the existing log settings for CRS

### ISSUE THREAD

**Issue by dextermallo** [dextermallo/GSoC-2023#4]
e.g., can the log be set to milliseconds?

**Comment by dexter-ys** [comment]
## Log-related

### ModSecurity (v2.x)

### ModSecurity (v3.x)

### Coraza

## Performance-related

### ModSecurity (v2.x)

`--enable-pcre-jit` - Enables JIT support from pcre >= 8.20 that can improve regex performance.
`--enable-lua-cache` - Enables lua vm caching that can improve lua script performance. Difference just appears if ModSecurity must run more than one script per transaction.

- [SecDebugLogLevel](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#secdebugloglevel)
- [SecRulePerfTime](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#secdebugloglevel)
- [PERF_ALL](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#perf_all)
- [PERF_COMBINED](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#perf_combined)
- ... And others from PREF family

### ModSecurity (v3.x)

- [SecDebugLogLevel](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v3.x)#secdebugloglevel)

### Coraza

- N/A

**Comment by dune73** [comment]
Everything ModSec 2.9 is in microseconds. Based on my experience it would be better to have nanoseconds since a naked SecRule statement used to take 0.5 microseconds to process when I tested this while writing the 2nd edition of the Handbook a few years ago.

If that is not feasible, you should stick with microseconds.

Unfortunately, ModSec3 does not implement the PERF_* group of variables. All you have is the clock running in DURATION. So what I usually do is using that as a timer. See rule 90000 and friends in https://www.netnea.com/cms/apache-tutorial-7_including-modsecurity-core-rules/.

**Comment by dexter-ys** [comment]
Primarily working on other utils instead of the logs right now, I will close this ticket :)
